<?php
/*
* do not edit this file without my permission	
* Created By ArunDev
*/
if(isset($_GET['token'])){
	if($_GET['token']=="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6ImFydW5kZXYifQ.i7Fl7vUNAr3yabWEJcwO80KZFhoIxX0QgEneoaoaNqg"){
		$servername = "localhost";
		$username = "pretally";
		$password = "Pretally@2021$#";

		// Create connection
		$conn = mysqli_connect($servername, $username, $password,"pretally");
		// Check connection
		if ($conn->connect_error) {
		  die("Connection failed: " . $conn->connect_error);
		}

		$sql="select * from muble_attendance";
		$result = mysqli_query($conn,$sql) or die(mysqli_error($conn)); 
		$emparray = array();
		while($row =mysqli_fetch_assoc($result))
		{
		    $emparray[] = $row;
		}
		header('Content-Type: application/json; charset=utf-8');
		echo json_encode($emparray);
		mysqli_close($conn);
	}
	else{
		header('Content-Type: application/json; charset=utf-8');
		echo "Invalid token";
	}
}
else{
	http_response_code(403);
	die('Forbidden');
}
?>
